image: python:3.8-slim

pipelines:
  branches:
    master:
      - step:
          name: test
          services:
            - postgres
          script:
            - pip install -r requirements.txt
            - export ENVIRONMENT=TEST
            - export DB_PORT=5432
            - export REDIS_PORT=6379
            - export DB_USER=postgres
            - pytest
      - step:
          name: build
          services:
            - docker
          script:
            - export TAG=latest
            - export IMAGE_NAME=$DOCKER_IMAGE_NAME:$TAG
            - docker build -t $IMAGE_NAME .
            - pipe: atlassian/aws-ecr-push-image:1.1.3
              variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  IMAGE_NAME: $IMAGE_NAME
    development:
      - step:
          name: test
          services:
            - postgres
          script:
            - pip install -r requirements.txt
            - export ENVIRONMENT=TEST
            - export DB_PORT=5432
            - export REDIS_PORT=6379
            - export DB_USER=postgres
            - pytest
      - step:
          name: build
          services:
            - docker
          script:
            - export TAG=staging
            - export IMAGE_NAME=$DOCKER_IMAGE_NAME:$TAG
            - docker build -t $IMAGE_NAME .
            - pipe: atlassian/aws-ecr-push-image:1.1.3
              variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  IMAGE_NAME: $IMAGE_NAME
                  TAGS: $TAG

definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
